version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: woow_postgres
    restart: always
    environment:
      POSTGRES_USER: woow
      POSTGRES_PASSWORD: woow
      POSTGRES_DB: woow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: